name: Build and Release DEB Package

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.19'

      - name: Build and Create DEB Package
        run: |
          sudo apt-get update
          sudo apt-get install -y dh-make debhelper
          TAG_NAME=${GITHUB_REF##*/}
          dpkg-buildpackage -us -uc
      - name: Upload DEB Package to GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./deeplx-${{ steps.extract_tag.outputs.tag }}.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
